feat: process registry delete kli support
konstellation-io/kai-kli pull request #108
Opened 2024-02-15 15:31 UTC by alexrodfe

## Description

- Add command for delete process
- Added api, service, command and renderer layers

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2024-02-16 13:38 UTC, JYisus submitted a review, later dismissed

2024-02-16 13:38 UTC, kafkaphoenix submitted a review, later dismissed

2024-02-16 13:39 UTC, kafkaphoenix commented
good job!

2024-02-16 14:25 UTC, dfinteligenz requested changes

2024-02-16 14:25 UTC, dfinteligenz commented on internal/render/json-renderer.go
> +		r.jsonWriter.KeyValue("Message", fmt.Sprintf("Process %s created!", process.Name))
We are using the message for error messages only, if the status is OK, the expected response is an empty Message and the Data field with the response.
```suggestion
		r.jsonWriter.KeyValue("Message", "")
```

2024-02-16 14:25 UTC, dfinteligenz commented on internal/render/json-renderer.go
> +		r.jsonWriter.KeyValue("Message", fmt.Sprintf("Process %s deleted!", process))
Ditto
```suggestion
		r.jsonWriter.KeyValue("Message", "")
```

2024-02-20 11:12 UTC, kafkaphoenix approved these changes

2024-02-20 11:23 UTC, dfinteligenz approved these changes

2024-02-20 11:38 UTC, merged