Add login command
konstellation-io/kai-kli pull request #12
Opened 2023-07-17 11:54 UTC by dfinteligenz

## Description
- Add logging command for the servers.
- Export KAI authentication to it's own package for managing server login and token retrieval
- Export the KAI configuration management service to it's own package
- Add authentication middleware based on command labels for future commands.

## Motivation and Context
As the KLI evolves, we need to 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [x] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-07-17 17:01 UTC, JYisus requested changes

2023-07-18 05:54 UTC, dfinteligenz commented on cmd/server/login.go
> +		Use: "login <remote_name> [--user <username>] +" +
Good catch, you are totally right :)

2023-07-18 06:02 UTC, dfinteligenz commented on internal/render/renderer.go
> +			fmt.Sprintf("%t", s.Token != nil && s.Token.AccessToken != ""),
Agreed

2023-07-18 06:38 UTC, dfinteligenz commented on internal/services/authentication/authentication_service.go
> +	return server.Username != "" && server.Password != "" && server.Realm != "" && server.ClientID != ""
It is just the opposite, if none is "" it will be valid

2023-07-18 11:43 UTC, JYisus commented on internal/services/authentication/authentication_service.go
> +	return server.Username != "" && server.Password != "" && server.Realm != "" && server.ClientID != ""
Ahhh, true, my bad, I read wrong the function name jajajaja

2023-07-18 11:44 UTC, JYisus approved these changes
Good Job!

2023-07-18 12:13 UTC, kafkaphoenix approved these changes

2023-07-18 13:41 UTC, merged