feat: List process registry command
konstellation-io/kai-kli pull request #31
Opened 2023-08-28 15:39 UTC by alexrodfe

## Description

- Added list process registry command

## Motivation and Context

Users will be able to list process registries from a desired product. This list can also be filtered by process type.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [X] I have created tests for my code changes, and the tests are passing.
- [X] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-08-29 06:37 UTC, kafkaphoenix submitted a review, later dismissed

2023-08-29 06:58 UTC, dfinteligenz requested changes

2023-08-29 06:58 UTC, dfinteligenz commented on api/process-registry/list.go
> +			processRegistries(productID: $productID, processType: $processType) {
```suggestion
			registeredProcesses(productID: $productID, processType: $processType) {
```

2023-08-29 06:58 UTC, dfinteligenz commented on cmd/process-registry/process_registry.go
> +			$ kli process-registry ls <product_id> [--type <process_type>] [opts...]
```suggestion
			$ kli process-registry ls <product_id> [opts...]
```

2023-08-29 06:58 UTC, dfinteligenz commented on internal/render/interface.go
> +	RenderProcessRegistries(registries []registry.ProcessRegistry)
```suggestion
	RenderRegisteredProcesses(registries []registry.ProcessRegistry)
```

2023-08-31 10:45 UTC, JYisus approved these changes

2023-08-31 11:27 UTC, alexrodfe commented
Moved to https://github.com/konstellation-io/kai-kli/pull/35

2023-08-31 11:27 UTC, closed without merging