feat: implement add server functionality and partial config refactor
konstellation-io/kai-kli pull request #6
Opened 2023-07-03 13:08 UTC by JYisus

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [x] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [x] I have updated the documentation accordingly.

2023-07-06 06:13 UTC, dfinteligenz requested changes

2023-07-06 06:13 UTC, dfinteligenz commented on cmd/server/add.go
> +    $ kli server add my-server http://api.local.kre
```suggestion
    $ kli server add my-server http://api.local.kai
```

2023-07-06 06:13 UTC, dfinteligenz commented on cmd/server/server.go
> +			$ kli server add my-server http://api.kre.local
```suggestion
			$ kli server add my-server http://api.kai.local
```

2023-07-08 19:05 UTC, JYisus commented on internal/server/add.go
> +func (c *KaiConfigurator) AddNewServer(server Server, isDefault bool) error {
setDefault seems more like a function name, maybe we should change the cmd

2023-07-11 12:21 UTC, closed without merging