Add remove server command
konstellation-io/kai-kli pull request #9
Opened 2023-07-10 21:27 UTC by dfinteligenz

## Description
Add remove server command

## Motivation and Context
The remove server command should remove an existing server from the server list.
If the server to be removed is defined as the default, the first server from the list will be defined as the new default.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [x] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-07-10 21:50 UTC, JYisus requested changes

2023-07-10 21:50 UTC, JYisus commented on cmd/server/remove.go
> +	server2 "github.com/konstellation-io/kli/internal/server"
Keep this import as server and change the name of the server var

2023-07-10 21:50 UTC, JYisus commented on cmd/server/remove.go
> +		Use:     "remove <remote_name>",
remote_name or server_name?

2023-07-10 21:50 UTC, JYisus commented on cmd/server/remove.go
> +	cmd.Flags().BoolP(_defaultFlag, "d", false, "Set the current server as the default server.")
If the server is being deleted this flag doesn't make sense

2023-07-10 21:50 UTC, JYisus commented on internal/configuration/kai_server_configuration.go
> +	for i, serv := range kc.Servers {
We could extract this to a function like findServer or something like that

2023-07-10 21:50 UTC, JYisus commented on internal/configuration/kai_server_configuration.go
> +	for i, serv := range kc.Servers {
we can have find function that returns the index and an error if the server doesn't exist, and use it instead of checkServerExists

2023-07-10 21:50 UTC, JYisus commented on internal/server/remove.go
> +	if !config.CheckServerExists(server) {
Is this being checked twice? One here and the inside the deleteServer function

2023-07-12 14:23 UTC, alexrodfe commented on api/kai/kai_mocks_test.go
> +	config2 "github.com/konstellation-io/kli/cmd/config"
Several times I see this. For packages importing cmd and kai config we could have packages renamed to:
- kaiconfig
- kliconfig or cmdconfig

So configs are better distinguished

2023-07-12 14:50 UTC, alexrodfe commented on internal/server/list_test.go
> +package server_test
check out test files, some of them are missing go build tags

2023-07-12 14:52 UTC, alexrodfe submitted a review, later dismissed
Great! Just a couple of notes

2023-07-12 18:02 UTC, dfinteligenz commented on api/kai/kai_mocks_test.go
> +	config2 "github.com/konstellation-io/kli/cmd/config"
The `kliconfig` will eventually be deleted, as every configuration will be replaced by Viper, so I'd leave it as is, and when replaced fix any naming issues.

2023-07-12 18:05 UTC, dfinteligenz commented on internal/server/list_test.go
> +package server_test
The unit/integration test separation is not done in this repository yet.
I will eventually add it when we add any integration tests in a future PR.

2023-07-13 08:58 UTC, alexrodfe submitted a review, later dismissed
Lets ship it :sunglasses:

2023-07-13 09:21 UTC, alexrodfe submitted a review, later dismissed

2023-07-13 09:27 UTC, alexrodfe approved these changes

2023-07-13 09:28 UTC, alexrodfe approved these changes
Approval

2023-07-13 10:14 UTC, alexrodfe submitted a review, later dismissed
sfdzvcxvcvxcvb

2023-07-13 12:47 UTC, JYisus approved these changes

2023-07-13 12:47 UTC, kafkaphoenix approved these changes

2023-07-13 13:11 UTC, closed without merging